#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 10 15:17:07 2022

@author: tobou
"""


import os
import numpy as np
import pandas as pd

import sys
sys.path.insert(0, '..')



def aux_df(name, dirname, columns, start=None, end=None):

    df= pd.read_table(name, dtype=float, header=None, names= columns,sep='\s+').fillna(np.nan)
    
    df =pd.read_table('ER5_0610.dat',dtype=float, header=None, sep='\s+' ,
                       names=['timestamp', 'b', 'station', 'p_max' , 'c', 't1',
                              't2', 't3', 'i', 'j', 'k', 'l','m', 'p_min'])
    
    df['timestamp'] = pd.to_datetime(df['timestamp'], format='%Y%m%d%H%M')
    if(start):
        df= df[df['timestamp']>=start]
    elif(end):
        df= df[df['timestamp']<=end]
    df['file_type']= dirname
    return df



def Create_df(variable, start=None, end=None):
    df=pd.DataFrame();
    
    if(variable== 'Press'):
        columns=['station','timestamp','min', 'max']
    if(variable== 't2m'):
        columns=['station','timestamp','min', 'max', 'staturation']
    for dirname, _, filenames in os.walk('../data_files/model_pred'):
        for filename in filenames:
            datetime_str= filename.split('.', 1)[0].replace('ER5_', '').replace('EC9_', '')


            try:
                datetime_str= filename.split('.', 1)[0].replace('ER5_', '').replace('EC9_', '')
                
                if(int(datetime_str[0:2])<23):
                    datetime_str='20'+datetime_str[0:2]+'-'+datetime_str[2:4] 
                else:
                    datetime_str='19'+datetime_str[0:2]+'-'+datetime_str[2:4]
                date=np.datetime64(datetime_str)
                
                if(str(variable) in filename):
                    if(start and date<start):
                        continue
                    elif(end and date>end):
                        continue
                    

                    df2=aux_df(str(dirname+'/'+filename), dirname, columns, start, end)
                    df=df.append(df2, ignore_index=True)
            except:
                
                pass                       
            
            
    #df_true= df[df['file_type']=='../data_files/data/Carra'] # Corrected data from Bjarne
    #df=df[df['file_type']=='/home/tobou/data/combined']

    return df



df= Create_df('Press', start=np.datetime64('1999-10-01'), end=np.datetime64('1999-12-31')).to_pickle('/home/tobou/Desktop/Meteorological_Data_quality_assesment/df_gen/model_pred.pkl')





